
services:

  dns-server:
    image: $REGISTRY/kubedock-dns:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: $REGISTRY/kubedock-dns-base:1.0.0
    ports:
      - 1053:1053/udp
      - 8443:8443
   

