---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedock-dns-mutator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubedock-dns-mutator
rules:
  - apiGroups:
      - ""
    resources:
      - services
    resourceNames:
      - dns-server
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubedock-mutator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubedock-dns-mutator
subjects:
  - kind: ServiceAccount
    name: kubedock-dns-mutator
    namespace: {{ .Release.Namespace }}
