---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedock-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubedock-dns
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    resourceNames:
      - dns
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubedock-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubedock-dns
subjects:
  - kind: ServiceAccount
    name: kubedock-dns
    namespace: {{ .Release.Namespace }}
