---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedock-dns-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubedock-dns-server
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    resourceNames:
      - dns-server
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubedock-dns-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubedock-dns-server
subjects:
  - kind: ServiceAccount
    name: kubedock-dns-server
    namespace: {{ .Release.Namespace }}
