apiVersion: v1
entries:
  kubedock-dns:
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2025-01-18T20:50:55.903462604Z"
    description: Kubedock DNS
    digest: 4542f4ba585e6278414002a7034088f07a78f3c33c6edacb38ef11542f677e10
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2025-01-18T20:50:55.903235897Z"
    description: Kubedock DNS
    digest: f1c8dc2190eb35adae4acc4a8cd0ff0fc7a3e3c6381929e5754496d645610065
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2025-01-18T20:50:55.90297163Z"
    description: Kubedock DNS
    digest: a7bb0da9f3a5622a18caaafbdbcac3f8540e2a99d2f210b3700e925bdaecf5af
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.0.2
    created: "2025-01-18T20:50:55.902752858Z"
    description: Kubedock DNS
    digest: ddae0b00fedde302dd51dd115169661e82e5676e10e4c27ac62f269117766600
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.0.0-naming
    created: "2025-01-18T20:50:55.902528847Z"
    description: Kubedock DNS
    digest: 4a779f0445c690a1f604219c31847f9d2e5cc03bfa277c87042e0c37ac57c4f5
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.0-naming.tgz
    version: 0.0.0-naming
  - apiVersion: v2
    appVersion: 0.0.0-main
    created: "2025-01-18T20:50:55.902287953Z"
    description: Kubedock DNS
    digest: 25556070278d51c8b1c03275b52d52f0615d92adcd994619abdec552c697a0ea
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.0-main.tgz
    version: 0.0.0-main
  - apiVersion: v2
    appVersion: 0.0.0-ghactions
    created: "2025-01-18T20:50:55.901976938Z"
    description: Kubedock DNS
    digest: 38f96d10a6d5d773bc477faa091c3f723257f2e4b51eee879f1d04e13e5b03c6
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.0-ghactions.tgz
    version: 0.0.0-ghactions
generated: "2025-01-18T20:50:55.901503788Z"
