apiVersion: v1
entries:
  kubedock-dns:
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2024-12-08T14:46:59.867866701Z"
    description: Kubedock DNS
    digest: 4542f4ba585e6278414002a7034088f07a78f3c33c6edacb38ef11542f677e10
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2024-12-08T14:46:59.867590516Z"
    description: Kubedock DNS
    digest: f1c8dc2190eb35adae4acc4a8cd0ff0fc7a3e3c6381929e5754496d645610065
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2024-12-08T14:46:59.867355148Z"
    description: Kubedock DNS
    digest: a7bb0da9f3a5622a18caaafbdbcac3f8540e2a99d2f210b3700e925bdaecf5af
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.0.2
    created: "2024-12-08T14:46:59.86714176Z"
    description: Kubedock DNS
    digest: ddae0b00fedde302dd51dd115169661e82e5676e10e4c27ac62f269117766600
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.0.0-main
    created: "2024-12-08T14:46:59.866917692Z"
    description: Kubedock DNS
    digest: 4b24bf7622e9831b5e09d8d5f289b2f88a262f9c34af54230fe370db52fc5f63
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.0-main.tgz
    version: 0.0.0-main
  - apiVersion: v2
    appVersion: 0.0.0-ghactions
    created: "2024-12-08T14:46:59.866695699Z"
    description: Kubedock DNS
    digest: 878ece46d96f822e953a2eb641c3879609c81ddfb7ab9b6f1ef55c4e15f85e91
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.0-ghactions.tgz
    version: 0.0.0-ghactions
generated: "2024-12-08T14:46:59.866298939Z"
