apiVersion: v1
entries:
  kubedock-dns:
  - apiVersion: v2
    appVersion: 0.0.6+ghactions
    created: "2025-02-06T22:14:02.06249363Z"
    description: Kubedock DNS
    digest: a54486c68507e08260466cb601ab8e5523541a820535709b4fb20aa772029785
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.6+ghactions.tgz
    version: 0.0.6+ghactions
  - apiVersion: v2
    appVersion: 0.0.6
    created: "2025-02-06T22:14:02.062977714Z"
    description: Kubedock DNS
    digest: 0acbedbf069b3fb667d8a985261d2cc82d2b562a78c0a8fb5c4c451f27bde45e
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v2
    appVersion: 0.0.6-ghactions
    created: "2025-02-06T22:14:02.062743546Z"
    description: Kubedock DNS
    digest: 8e3c5494346cbb4e9100110243b103b043e58ccc1b0c376e10ebcbd5b113c9a7
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.6-ghactions.tgz
    version: 0.0.6-ghactions
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2025-02-06T22:14:02.062274361Z"
    description: Kubedock DNS
    digest: 4542f4ba585e6278414002a7034088f07a78f3c33c6edacb38ef11542f677e10
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2025-02-06T22:14:02.061838491Z"
    description: Kubedock DNS
    digest: f1c8dc2190eb35adae4acc4a8cd0ff0fc7a3e3c6381929e5754496d645610065
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2025-02-06T22:14:02.061402287Z"
    description: Kubedock DNS
    digest: a7bb0da9f3a5622a18caaafbdbcac3f8540e2a99d2f210b3700e925bdaecf5af
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.0.2
    created: "2025-02-06T22:14:02.060736806Z"
    description: Kubedock DNS
    digest: ddae0b00fedde302dd51dd115169661e82e5676e10e4c27ac62f269117766600
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.0.0+ghactions
    created: "2025-02-06T22:14:02.059605195Z"
    description: Kubedock DNS
    digest: acd2499da4c331a2ef8dd0c7eaad42408e53285fdc1ca8df433f4cf59260ac29
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.0+ghactions.tgz
    version: 0.0.0+ghactions
  - apiVersion: v2
    appVersion: 0.0.0-naming
    created: "2025-02-06T22:14:02.06052494Z"
    description: Kubedock DNS
    digest: 4a779f0445c690a1f604219c31847f9d2e5cc03bfa277c87042e0c37ac57c4f5
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.0-naming.tgz
    version: 0.0.0-naming
  - apiVersion: v2
    appVersion: 0.0.0-main
    created: "2025-02-06T22:14:02.06030506Z"
    description: Kubedock DNS
    digest: 0ab96e78903fc3fcbdb2fde95f1ab08ebf189b7e11eeaecdb61fbbe650d1a3c3
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.0-main.tgz
    version: 0.0.0-main
  - apiVersion: v2
    appVersion: 0.0.0-ghactions
    created: "2025-02-06T22:14:02.060089388Z"
    description: Kubedock DNS
    digest: aae42a0d7bb49cc3211953098c33ae139b184fa15d68a96f665f812065d470b7
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.0-ghactions.tgz
    version: 0.0.0-ghactions
  - apiVersion: v2
    appVersion: 0.0.0-0.0.0+ghactions
    created: "2025-02-06T22:14:02.059857836Z"
    description: Kubedock DNS
    digest: 67650a804453c2c73605d5a65d9416819fa0129fea5a60cfaead54f23f34ddf0
    name: kubedock-dns
    type: application
    urls:
    - https://ErikEngerd.github.io/kubedock-dns/charts/kubedock-dns-0.0.0-0.0.0+ghactions.tgz
    version: 0.0.0-0.0.0+ghactions
generated: "2025-02-06T22:14:02.05922243Z"
