apiVersion: v1
kind: Pod
metadata:
  name: {{ .Name }}
  labels:
    {{ .LabelName }}: "{{ .Enabled }}"
  annotations:
    {{- range $idx, $host := .HostAliases }}
    kubedock.hostalias/{{ $idx }}: "{{ $host }}"
    {{- end }}
    {{- range $idx, $net := .Networks }}
    kubedock.network/{{ $idx }}: "{{ $net }}"
    {{- end }}
spec:
  containers:
  - name: app
    image: test/dnsclient:latest
    args:
      - "{{ .ShutdownTimeout }}"
      - "{{ .Ready }}"
      - "tail"
      - "-f"
      - "/dev/null"
    readinessProbe:
      exec:
        command: ["/bin/sh", "-c", "test -f /app/ready"]
      initialDelaySeconds: 1
      periodSeconds: 1
      failureThreshold: 1
      successThreshold: 1
