name: Checkin pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  call-pipeline:
    uses: ./.github/workflows/pipeline.yaml
    permissions:
      packages: write
      contents: write
      id-token: write
      actions: read
    secrets: inherit
    with:
      version: ${{ github.ref_name }}-latest