name: Checkin pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

  pull_request:
    branches:
      - main
jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - id: set-version
        name: set-version
        run: |
          VERSION="${{ github.ref_name }}" 
          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT
          

  call-pipeline:
    needs: set-version
    uses: ./.github/workflows/pipeline.yaml
    permissions:
      packages: write
      contents: write
    secrets: inherit
    with:
      version: ${{ needs.set-version.outputs.version }}