name: Checkin pipeline

on:
  push:
    branches:
      - '**'
      # for testing.
      - ghactions
    tags:
      - 'v*'

  pull_request:
    branches:
      - main
jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - id: set-version
        name: set-version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            # Case 1: Tag push - use the tag name without 'v' prefix
            VERSION="${{ github.ref_name }}"
            VERSION="${VERSION#v}"
          else
            # Case 2: Branch push - get latest tag + branch name
            LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
            BRANCH="${{ github.ref_name }}"
            VERSION="${LATEST_TAG#v}+${BRANCH}"
          fi
          echo "Using version ${VERSION#v}" 
          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT
          

  call-pipeline:
    needs: set-version
    uses: ./.github/workflows/pipeline.yaml
    permissions:
      packages: write
      contents: write
    secrets: inherit
    with:
      version: ${{ needs.set-version.outputs.version }}
