name: Checkin pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

  pull_request:
    branches:
      - main
jobs:
  set-version:
    runs-on: ubuntu-latest
    run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

  call-pipeline:
    uses: ./.github/workflows/pipeline.yaml
    permissions:
      packages: write
      contents: write
    secrets: inherit
    with:
      version: ${{ env.VERSION }}