name: Go CI/CD Pipeline

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  HELM_CHART_PATH: ./helm/kubedock-dns
  GO_VERSION: '1.23'
  HELM_REPO_SUBDIR: charts  # Subdirectory for Helm charts in gh-pages
  VERSION: ${{ inputs.version }}

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: debug-info
        run: |
            echo "Registry: ${{ env.REGISTRY }}"
            echo "Image name: ${{ env.IMAGE_NAME }}"
            echo "Version: ${{ env.VERSION }}"
            echo "Actor: ${{ github.actor }}"

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt

  docker-build-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags:  ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  helm-package-publish:
    needs: docker-build-push
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Package Helm chart
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "This is a tag build"
            export HELMVERSION=${{ env.VERSION }}
          else
            echo "This is a snapshot build"
            export HELMVERSION=0.0.0-${{ env.VERSION }}
          fi
          yq eval '.version = strenv(HELMVERSION)' -i ${{ env.HELM_CHART_PATH }}/Chart.yaml
          yq eval '.appVersion = strenv(HELMVERSION)' -i ${{ env.HELM_CHART_PATH }}/Chart.yaml
          export LIBRARY="${{ env.REGISTRY }}/${{ github.repository_owner }}"
          LIBRARY="$( echo "$LIBRARY" | tr '[:upper:]' '[:lower:]' )"
          yq eval '.registry = strenv(LIBRARY)' -i ${{ env.HELM_CHART_PATH }}/values.yaml
          yq eval '.version = strenv(VERSION)' -i ${{ env.HELM_CHART_PATH }}/values.yaml
          yq eval '.replicas = 2' -i ${{ env.HELM_CHART_PATH }}/values.yaml

          helm package ${{ env.HELM_CHART_PATH }} --destination .chart-archive

      - name: Check out GitHub Pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update Helm repository
        run: |
          mkdir -p gh-pages/${{ env.HELM_REPO_SUBDIR }}
          cp .chart-archive/*.tgz gh-pages/${{ env.HELM_REPO_SUBDIR }}/
          cd gh-pages/${{ env.HELM_REPO_SUBDIR }}
          helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ env.HELM_REPO_SUBDIR }}
          cd ..
          git add .
          git commit -m "Update Helm chart repository"
          git push


